### ISSUE TITLE
[Feature Request]Implement a BitMap

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework-commons#16]
# Feature Request

**Describe the Feature Request**

Implement a BitMap like

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/BitMaps.sol

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by djy0** [comment]
@jolestar Hi, could you tell me which type is suitable for as a map here, seems I can not use std:table for now.

**Comment by jolestar** [comment]
> @jolestar Hi, could you teach me which type is suitable for using as a mapping here, seems I can not use std::table (or extension::table) for now.

Use a vector<u8>? if the bitmap is not too big, vector<u8> is more suitable.

**Comment by 0xpause** [comment]
Close as the issue was completed.
