### ISSUE TITLE
[Feature Request] Implement some String Helper function

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework-commons#17]
# Feature Request

**Describe the Feature Request**

Implement some String Helper function like

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by djy0** [comment]
I am working on this
