### ISSUE TITLE
[Feature Request] StringUtil support u256

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework-commons#23]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by JerryKwan** [comment]
@jolestar Would you please elaborate on this feature? thank you

**Comment by jolestar** [comment]
> @jolestar Would you please elaborate on this feature? thank you

https://github.com/starcoinorg/starcoin-framework-commons/blob/main/sources/StringUtil.move

```
to_string(value: U256):String
to_hex_string(value: U256):String
```
