### ISSUE TITLE
[Feature Request] Escrow

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework-commons#28]
# Feature Request

**Describe the Feature Request**

Implement an escrow module to holds funds designated for a payee until they  withdraw them.

reference: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/escrow/Escrow.sol

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by jiangying000** [comment]
work
