### ISSUE TITLE
[Feature Request] TimeHelper 

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework-commons#31]
# Feature Request

**Describe the Feature Request**

It is annoying and error-prone  counting milliseconds every time when dealing with timestamp Counting milliseconds every time.  

Please provide a TimeHelper to return milliseconds/seconds for <N>  minute，<N> hour，<N> day，<N> week. 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by YusongWang** [comment]
work
