### ISSUE TITLE
[Feature Request] TokenLocker

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework-commons#32]
# Feature Request

**Describe the Feature Request**

Implement a token locker to lock the given token for a period of time.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by YusongWang** [comment]
work
