### ISSUE TITLE
[Feature Request] Migrate EthStateVerifier,MerkleDistributor,StarcoinVerifier from starcoin repo

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework-commons#5]
# Feature Request

Migrate EthStateVerifier,MerkleDistributor,StarcoinVerifier from https://github.com/starcoinorg/starcoin/tree/master/contrib-contracts and rewrite the test with move integration-test.

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by 0xpause** [comment]
This issue is completed and should be closed.
