### ISSUE TITLE
MoveFunsDAO 重构及品牌重塑意见收集

### ISSUE THREAD

**Issue by 10xhunter** [starcoinorg/starcoin-framework-commons#69]
出于实现组织长久化和组织成员利益最大化的考虑，本人提议对 MoveFunsDAO 组织架构进行重构，将 MoveFunsDAO 现有资源进行统一规划整合，构建一个公平、共利和充满活力的社区；

同时，立足于 Web3 浪潮的早期阶段，Move 语言生态中仍然有大量的基础设施工作需要补足，这些工作中蕴藏了巨大的机会，重构后的 DAO 将以抓住这些机会为目标，故此考虑对 MoveFuns 品牌进行重塑，以反映这一目标。

如果你对 MoveFunsDAO 的发展有任何意见，欢迎提供反馈，以便加入到重构过程中。

意见收集有效期为七天。

**Comment by jolestar** [comment]
是不是放到一个治理的仓库或者 discussions 里更合适？

**Comment by 10xhunter** [comment]
> 是不是放到一个治理的仓库或者 discussions 里更合适？

这个暂时先这样，后续该用什么工具还要研究下。

**Comment by nangongamo** [comment]
貌似各成员都散了吧，王校长要组织起来，其实还是能做些事的。

**Comment by jolestar** [comment]
没有散，最近忙没顾上。大家一起策划一下，春节后组织起来。

> 貌似各成员都散了吧，王校长要组织起来，其实还是能做些事的。
